apiVersion: apps/v1
kind: Deployment
metadata:
  name: atal
  labels:
    app: test
  namespace: development
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: sales-app-container
        image: tomcat
        ports:
        - containerPort: 80
